stackName: sdoneks
modelBucketArn: arn:aws:s3:::sdoneks-model-bucket-51a6
clusterComponents:
  instanceType: m7g.large
  desiredCount: 2
APIGW:
  stageName: dev
  throttle:
    rateLimit: 30
    burstLimit: 50
modelsRuntime:
- name: sdruntime
  namespace: default
  modelFilename: sd_xl_turbo_1.0.safetensors
  dynamicModel: false
  type: sdwebui
  extraValues:
    karpenter:
      nodeTemplate:
        amiFamily: Bottlerocket
      provisioner:
        instanceType:
        - g6.2xlarge
        - g5.2xlarge
        capacityType:
          onDemand: true
          spot: true
    runtime:
      scaling:
        queueLength: 10
        minReplicaCount: 0
        maxReplicaCount: 5
        cooldownPeriod: 300
