{{- if and (.Values.runtime.persistence.enabled) (.Values.runtime.persistence.s3.enabled) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sdchart.fullname" . }}-s3-model-volume
  {{- if .Values.runtime.persistence.annotations }}
  annotations:
  {{ toYaml .Values.runtime.persistence.annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
  {{- if .Values.runtime.labels }}
  {{- toYaml .Values.runtime.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.runtime.persistence.labels }}
  {{- toYaml .Values.runtime.persistence.labels | nindent 4 }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.runtime.persistence.size }}
  accessModes:
  {{- toYaml .Values.runtime.persistence.accessModes | nindent 2 }}
  mountOptions:
  - allow-delete
  - allow-other
  - file-mode=777
  - dir-mode=777
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: {{ .Values.runtime.persistence.s3.modelBucket }}
{{- end }}